# Generated by Django 3.2.7 on 2022-03-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0002_contactus_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='subject',
            new_name='message',
        ),
    ]
