# Generated by Django 3.2.7 on 2022-03-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0004_auto_20220320_0320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
    ]
