# Generated by Django 3.2.7 on 2022-03-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0005_rename_animals_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
    ]
