# Generated by Django 3.2.7 on 2022-03-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_App', '0006_delete_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(max_length=3000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('slug', models.CharField(max_length=48)),
            ],
        ),
    ]
